version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - db_data:/data

volumes:
  db_data: